version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: roxilerDB
    ports:
      - "8090:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
